apiVersion: v1
kind: Namespace
metadata:
  name: test-ns-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-ns-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /run
              name: nginx-run
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}


---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test-ns-1
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80